/**
 * MetaForge Database Schema Generator
 *
 * Generates Prisma schema from MetaForge entity config.
 * Maps config field types to PostgreSQL column types.
 */
// ─── Type Mappings ───────────────────────────────────────────────
const FIELD_TYPE_MAP = {
    string: { prismaType: 'String', dbType: 'VARCHAR(255)' },
    text: { prismaType: 'String', dbType: 'TEXT' },
    number: { prismaType: 'Float', dbType: 'DECIMAL(18,6)' },
    boolean: { prismaType: 'Boolean', dbType: 'BOOLEAN', constraints: 'NOT NULL DEFAULT false' },
    date: { prismaType: 'DateTime', dbType: 'TIMESTAMPTZ' },
    email: { prismaType: 'String', dbType: 'VARCHAR(320)' },
    uuid: { prismaType: 'String', dbType: 'UUID', constraints: 'NOT NULL DEFAULT gen_random_uuid()' },
    json: { prismaType: 'Json', dbType: 'JSONB' },
    url: { prismaType: 'String', dbType: 'VARCHAR(2048)' },
    phone: { prismaType: 'String', dbType: 'VARCHAR(20)' },
    password: { prismaType: 'String', dbType: 'VARCHAR(255)' },
    color: { prismaType: 'String', dbType: 'VARCHAR(7)' },
    currency: { prismaType: 'Float', dbType: 'DECIMAL(18,2)' },
    file: { prismaType: 'String', dbType: 'VARCHAR(2048)' },
    image: { prismaType: 'String', dbType: 'VARCHAR(2048)' },
};
// ─── Prisma Schema Generator ─────────────────────────────────────
export function generatePrismaSchema(entities, tenantAware = true) {
    const lines = [];
    // Datasource & generator
    lines.push(`// Generated by MetaForge Database Architect`);
    lines.push(`// Do not edit manually — regenerated on each deploy\n`);
    lines.push(`generator client {`);
    lines.push(`  provider = "prisma-client-js"`);
    lines.push(`}\n`);
    lines.push(`datasource db {`);
    lines.push(`  provider = "postgresql"`);
    lines.push(`  url      = env("DATABASE_URL")`);
    lines.push(`}\n`);
    // Generate enum types
    entities.forEach(entity => {
        entity.fields.forEach(field => {
            if (field.type === 'enum' && field.enumValues?.length) {
                const enumName = `${capitalize(entity.name)}${capitalize(field.name)}`;
                lines.push(`enum ${enumName} {`);
                field.enumValues.forEach(v => lines.push(`  ${v.replace(/[^a-zA-Z0-9_]/g, '_')}`));
                lines.push(`}\n`);
            }
        });
    });
    // Generate models
    entities.forEach(entity => {
        lines.push(`model ${capitalize(entity.name)} {`);
        // Primary key
        lines.push(`  id        String   @id @default(uuid())`);
        // Tenant ID
        if (tenantAware) {
            lines.push(`  tenantId  String   @map("tenant_id")`);
        }
        // Fields
        entity.fields.forEach(field => {
            const mapping = FIELD_TYPE_MAP[field.type];
            if (!mapping && field.type !== 'enum')
                return;
            let prismaType;
            let attrs = [];
            if (field.type === 'enum' && field.enumValues?.length) {
                prismaType = `${capitalize(entity.name)}${capitalize(field.name)}`;
            }
            else {
                prismaType = mapping?.prismaType || 'String';
            }
            if (!field.required && field.type !== 'boolean') {
                prismaType += '?';
            }
            if (field.unique)
                attrs.push('@unique');
            if (field.default !== undefined) {
                if (typeof field.default === 'boolean') {
                    attrs.push(`@default(${field.default})`);
                }
                else if (typeof field.default === 'number') {
                    attrs.push(`@default(${field.default})`);
                }
                else if (typeof field.default === 'string') {
                    attrs.push(`@default("${field.default}")`);
                }
            }
            const attrStr = attrs.length > 0 ? ' ' + attrs.join(' ') : '';
            lines.push(`  ${padRight(field.name, 16)} ${padRight(prismaType, 12)}${attrStr}`);
        });
        // Relations
        (entity.relations || []).forEach(rel => {
            const targetModel = capitalize(rel.target);
            const fkName = rel.foreignKey || `${rel.name}Id`;
            if (rel.type === 'one-to-one' || rel.type === 'many-to-one') {
                lines.push(`  ${padRight(rel.name, 16)} ${padRight(targetModel + '?', 12)} @relation(fields: [${fkName}], references: [id], onDelete: ${mapOnDelete(rel.onDelete)})`);
                lines.push(`  ${padRight(fkName, 16)} String?`);
            }
            else if (rel.type === 'one-to-many') {
                lines.push(`  ${padRight(rel.name, 16)} ${targetModel}[]`);
            }
            else if (rel.type === 'many-to-many') {
                lines.push(`  ${padRight(rel.name, 16)} ${targetModel}[]`);
            }
        });
        // Timestamps
        if (entity.timestamps !== false) {
            lines.push(`  createdAt      DateTime @default(now()) @map("created_at")`);
            lines.push(`  updatedAt      DateTime @updatedAt @map("updated_at")`);
        }
        // Soft delete
        if (entity.softDelete) {
            lines.push(`  deletedAt      DateTime? @map("deleted_at")`);
        }
        // Table mapping
        lines.push(`\n  @@map("${entity.name}")`);
        // Tenant index
        if (tenantAware) {
            lines.push(`  @@index([tenantId])`);
        }
        lines.push(`}\n`);
    });
    return lines.join('\n');
}
// ─── SQL Migration Generator ─────────────────────────────────────
export function generateMigrationSQL(entities, tenantAware = true) {
    const statements = [];
    statements.push(`-- MetaForge Auto-Generated Migration`);
    statements.push(`-- Generated at: ${new Date().toISOString()}\n`);
    entities.forEach(entity => {
        const tableName = entity.name;
        const cols = [];
        cols.push(`  id UUID PRIMARY KEY DEFAULT gen_random_uuid()`);
        if (tenantAware) {
            cols.push(`  tenant_id VARCHAR(255) NOT NULL`);
        }
        entity.fields.forEach(field => {
            const mapping = FIELD_TYPE_MAP[field.type];
            if (!mapping && field.type !== 'enum')
                return;
            let colType;
            if (field.type === 'enum' && field.enumValues?.length) {
                colType = `VARCHAR(100)`; // Simplified; could create custom ENUM type
            }
            else {
                colType = mapping?.dbType || 'VARCHAR(255)';
            }
            let constraints = '';
            if (field.required)
                constraints += ' NOT NULL';
            if (field.unique)
                constraints += ' UNIQUE';
            if (field.default !== undefined) {
                if (typeof field.default === 'boolean')
                    constraints += ` DEFAULT ${field.default}`;
                else if (typeof field.default === 'number')
                    constraints += ` DEFAULT ${field.default}`;
                else
                    constraints += ` DEFAULT '${field.default}'`;
            }
            cols.push(`  ${field.name} ${colType}${constraints}`);
        });
        if (entity.timestamps !== false) {
            cols.push(`  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`);
            cols.push(`  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`);
        }
        if (entity.softDelete) {
            cols.push(`  deleted_at TIMESTAMPTZ`);
        }
        statements.push(`CREATE TABLE IF NOT EXISTS ${tableName} (`);
        statements.push(cols.join(',\n'));
        statements.push(`);\n`);
        // Index on tenant_id
        if (tenantAware) {
            statements.push(`CREATE INDEX IF NOT EXISTS idx_${tableName}_tenant ON ${tableName}(tenant_id);\n`);
        }
    });
    // Relations (foreign keys)
    entities.forEach(entity => {
        (entity.relations || []).forEach(rel => {
            if (rel.type === 'one-to-one' || rel.type === 'many-to-one') {
                const fkName = rel.foreignKey || `${rel.name}_id`;
                statements.push(`ALTER TABLE ${entity.name} ADD COLUMN IF NOT EXISTS ${fkName} UUID REFERENCES ${rel.target}(id) ON DELETE ${(rel.onDelete || 'RESTRICT').toUpperCase()};`);
            }
        });
    });
    return statements.join('\n');
}
// ─── Helpers ─────────────────────────────────────────────────────
function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}
function padRight(s, len) {
    return s + ' '.repeat(Math.max(0, len - s.length));
}
function mapOnDelete(value) {
    const map = {
        cascade: 'Cascade',
        'set-null': 'SetNull',
        restrict: 'Restrict',
        'no-action': 'NoAction',
    };
    return map[value || 'restrict'] || 'Restrict';
}
//# sourceMappingURL=database.js.map