"use client";

import React, { useState } from "react";
import { apiUrl } from "@/lib/api";

interface GitHubExportModalProps {
  appId: string;
  appName: string;
  onClose: () => void;
}

export function GitHubExportModal({ appId, appName, onClose }: GitHubExportModalProps) {
  const [token, setToken] = useState("");
  const [repoName, setRepoName] = useState(
    appName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "metaforge-app"
  );
  const [isPrivate, setIsPrivate] = useState(true);
  const [description, setDescription] = useState(`${appName} — Generated by MetaForge`);
  const [step, setStep] = useState<"form" | "validating" | "exporting" | "success" | "error">("form");
  const [ghUser, setGhUser] = useState<{ login: string; name: string; avatarUrl: string; tokenType?: string; hasRepoScope?: boolean } | null>(null);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState("");

  async function validateToken() {
    if (!token.trim()) {
      setError("Please enter your GitHub Personal Access Token");
      return;
    }

    setStep("validating");
    setError("");

    try {
      const res = await fetch(apiUrl("/github/validate-token"), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ token: token.trim() }),
      });
      const json = await res.json();

      if (json.success) {
        setGhUser(json.data);
        // Warn about fine-grained tokens that might lack permissions
        if (json.data.tokenType === 'fine-grained') {
          setError('⚠️ Fine-grained token detected. If export fails, use a Classic token with "repo" scope instead.');
        }
        setStep("form");
      } else {
        setError(json.error?.message || "Invalid token");
        setStep("form");
      }
    } catch {
      setError("Failed to validate token. Check your network connection.");
      setStep("form");
    }
  }

  async function exportToGitHub() {
    setStep("exporting");
    setError("");

    try {
      const res = await fetch(apiUrl(`/github/export/${appId}`), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({
          token: token.trim(),
          repoName,
          isPrivate,
          description,
        }),
      });
      const json = await res.json();

      if (json.success) {
        setResult(json.data);
        setStep("success");
      } else {
        setError(json.error?.message || "Export failed");
        setStep("error");
      }
    } catch (err: any) {
      setError(err.message || "Export failed");
      setStep("error");
    }
  }

  const inputStyle = {
    backgroundColor: "var(--bg-overlay)",
    border: "1px solid var(--border-default)",
    color: "var(--text-primary)",
    borderRadius: "8px",
    padding: "10px 14px",
    fontSize: "13px",
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm">
      <div
        className="relative w-full max-w-lg overflow-hidden rounded-2xl"
        style={{
          backgroundColor: "var(--bg-elevated)",
          border: "1px solid var(--border-default)",
          boxShadow: "var(--shadow-lg)",
          animation: "mf-modal-in 200ms ease-out",
        }}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4" style={{ borderBottom: "1px solid var(--border-subtle)" }}>
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg" style={{ backgroundColor: "var(--bg-surface)", border: "1px solid var(--border-default)" }}>
              <svg className="h-5 w-5" style={{ color: "var(--text-secondary)" }} fill="currentColor" viewBox="0 0 24 24">
                <path fillRule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clipRule="evenodd" />
              </svg>
            </div>
            <div>
              <h3 className="text-[16px] font-bold" style={{ fontFamily: "var(--font-display)", color: "var(--text-primary)" }}>Export to GitHub</h3>
              <p className="text-[11px]" style={{ color: "var(--text-tertiary)" }}>Push {appName} to a GitHub repository</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 transition-all duration-[180ms]"
            style={{ color: "var(--text-tertiary)" }}
            onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-overlay)"; (e.currentTarget as HTMLElement).style.color = "var(--text-primary)"; }}
            onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.backgroundColor = "transparent"; (e.currentTarget as HTMLElement).style.color = "var(--text-tertiary)"; }}
          >
            <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="px-6 py-5">
          {step === "success" ? (
            <div className="text-center py-4">
              <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full" style={{ backgroundColor: "rgba(52,211,153,0.1)", border: "1px solid rgba(52,211,153,0.2)" }}>
                <svg className="h-7 w-7" style={{ color: "var(--success)" }} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h4 className="text-[18px] font-bold mb-2" style={{ fontFamily: "var(--font-display)", color: "var(--text-primary)" }}>Export Successful!</h4>
              <p className="text-[13px] mb-4" style={{ color: "var(--text-secondary)" }}>
                Your app has been pushed to GitHub with {result?.fileCount} files.
              </p>
              <a
                href={result?.url}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-lg px-5 py-2.5 text-[13px] font-semibold transition-all duration-[180ms]"
                style={{ backgroundColor: "var(--bg-surface)", border: "1px solid var(--border-default)", color: "var(--text-primary)" }}
                onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-strong)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-overlay)"; }}
                onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-default)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-surface)"; }}
              >
                <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 24 24">
                  <path fillRule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clipRule="evenodd" />
                </svg>
                Open {result?.repository}
              </a>
              <div className="mt-5 rounded-lg p-4 text-left" style={{ backgroundColor: "var(--bg-surface)", border: "1px solid var(--border-subtle)" }}>
                <div className="flex items-center justify-between text-[11px] mb-2">
                  <span style={{ color: "var(--text-tertiary)" }}>Branch</span>
                  <code style={{ fontFamily: "var(--font-mono)", color: "var(--text-secondary)" }}>{result?.branch}</code>
                </div>
                <div className="flex items-center justify-between text-[11px] mb-2">
                  <span style={{ color: "var(--text-tertiary)" }}>Commit</span>
                  <code style={{ fontFamily: "var(--font-mono)", color: "var(--text-secondary)" }}>{result?.commitSha?.substring(0, 8)}</code>
                </div>
                <div className="flex items-center justify-between text-[11px]">
                  <span style={{ color: "var(--text-tertiary)" }}>Files</span>
                  <span style={{ color: "var(--text-primary)" }}>{result?.fileCount} files</span>
                </div>
              </div>
            </div>
          ) : step === "error" ? (
            <div className="text-center py-4">
              <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full" style={{ backgroundColor: "rgba(248,113,113,0.1)", border: "1px solid rgba(248,113,113,0.2)" }}>
                <svg className="h-7 w-7" style={{ color: "var(--error)" }} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </div>
              <h4 className="text-[18px] font-bold mb-2" style={{ fontFamily: "var(--font-display)", color: "var(--text-primary)" }}>Export Failed</h4>
              <p className="text-[13px] mb-4" style={{ color: "var(--error)" }}>{error}</p>
              <button
                type="button"
                onClick={() => setStep("form")}
                className="rounded-lg px-5 py-2.5 text-[13px] font-semibold transition-all duration-[180ms]"
                style={{ backgroundColor: "var(--bg-surface)", border: "1px solid var(--border-default)", color: "var(--text-primary)" }}
                onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-strong)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-overlay)"; }}
                onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-default)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-surface)"; }}
              >
                Try Again
              </button>
            </div>
          ) : (
            <div className="space-y-4">
              {error && (
                <div className="rounded-lg px-4 py-2.5 text-[12px] font-medium" style={{ backgroundColor: "rgba(248,113,113,0.08)", border: "1px solid rgba(248,113,113,0.2)", color: "var(--error)" }}>
                  {error}
                </div>
              )}

              {/* Token Input */}
              <div>
                <label className="mb-1.5 block text-[11px] font-semibold uppercase" style={{ color: "var(--text-tertiary)", letterSpacing: "0.08em" }}>
                  GitHub Personal Access Token
                </label>
                <div className="flex gap-2">
                  <input
                    type="password"
                    value={token}
                    onChange={(e) => setToken(e.target.value)}
                    placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
                    className="flex-1 outline-none transition-all duration-[180ms]"
                    style={inputStyle}
                    onFocus={(e) => { (e.target as HTMLElement).style.borderColor = "var(--accent-primary)"; (e.target as HTMLElement).style.boxShadow = "0 0 0 3px var(--accent-muted)"; }}
                    onBlur={(e) => { (e.target as HTMLElement).style.borderColor = "var(--border-default)"; (e.target as HTMLElement).style.boxShadow = "none"; }}
                  />
                  <button
                    type="button"
                    onClick={validateToken}
                    disabled={step === "validating"}
                    className="rounded-lg px-4 text-[13px] font-semibold transition-all duration-[180ms] disabled:opacity-50"
                    style={{ backgroundColor: "var(--bg-surface)", border: "1px solid var(--border-default)", color: "var(--text-primary)" }}
                    onMouseEnter={(e) => { if (step !== "validating") { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-strong)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-overlay)"; } }}
                    onMouseLeave={(e) => { if (step !== "validating") { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-default)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-surface)"; } }}
                  >
                    {step === "validating" ? "..." : "Verify"}
                  </button>
                </div>
                <p className="mt-1.5 text-[10px]" style={{ color: "var(--text-tertiary)" }}>
                  Use a <strong style={{ color: "var(--text-secondary)" }}>Classic</strong> token with <code style={{ fontFamily: "var(--font-mono)" }}>repo</code> scope.{" "}
                  <a
                    href="https://github.com/settings/tokens/new?scopes=repo&description=MetaForge+Export"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="transition-colors duration-[180ms]"
                    style={{ color: "var(--accent-primary)", textDecoration: "none" }}
                    onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.color = "var(--accent-hover)"; (e.currentTarget as HTMLElement).style.textDecoration = "underline"; }}
                    onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.color = "var(--accent-primary)"; (e.currentTarget as HTMLElement).style.textDecoration = "none"; }}
                  >
                    Create token →
                  </a>
                </p>
              </div>

              {/* GitHub User Badge */}
              {ghUser && (
                <div className="flex items-center gap-3 rounded-lg px-4 py-3" style={{ backgroundColor: ghUser.tokenType === 'fine-grained' ? "rgba(251,191,36,0.05)" : "rgba(52,211,153,0.05)", border: `1px solid ${ghUser.tokenType === 'fine-grained' ? "rgba(251,191,36,0.2)" : "rgba(52,211,153,0.2)"}` }}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={ghUser.avatarUrl}
                    alt={ghUser.login}
                    className="h-8 w-8 rounded-full"
                    style={{ border: "1px solid var(--border-default)" }}
                  />
                  <div className="flex-1">
                    <div className="text-[13px] font-semibold" style={{ color: "var(--text-primary)" }}>{ghUser.name || ghUser.login}</div>
                    <div className="text-[11px]" style={{ color: ghUser.tokenType === 'fine-grained' ? "var(--warning)" : "var(--success)" }}>
                      @{ghUser.login} — {ghUser.tokenType === 'fine-grained' ? 'Fine-grained token' : 'Token verified ✓'}
                    </div>
                  </div>
                  {ghUser.tokenType === 'classic' && ghUser.hasRepoScope && (
                    <span className="rounded-md px-1.5 py-0.5 text-[10px] font-bold" style={{ backgroundColor: "rgba(52,211,153,0.1)", color: "var(--success)" }}>repo ✓</span>
                  )}
                </div>
              )}

              {/* Repo Name */}
              <div>
                <label className="mb-1.5 block text-[11px] font-semibold uppercase" style={{ color: "var(--text-tertiary)", letterSpacing: "0.08em" }}>
                  Repository Name
                </label>
                <input
                  type="text"
                  value={repoName}
                  onChange={(e) => setRepoName(e.target.value)}
                  className="w-full outline-none transition-all duration-[180ms]"
                  style={inputStyle}
                  onFocus={(e) => { (e.target as HTMLElement).style.borderColor = "var(--accent-primary)"; (e.target as HTMLElement).style.boxShadow = "0 0 0 3px var(--accent-muted)"; }}
                  onBlur={(e) => { (e.target as HTMLElement).style.borderColor = "var(--border-default)"; (e.target as HTMLElement).style.boxShadow = "none"; }}
                />
              </div>

              {/* Description */}
              <div>
                <label className="mb-1.5 block text-[11px] font-semibold uppercase" style={{ color: "var(--text-tertiary)", letterSpacing: "0.08em" }}>
                  Description
                </label>
                <input
                  type="text"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="w-full outline-none transition-all duration-[180ms]"
                  style={inputStyle}
                  onFocus={(e) => { (e.target as HTMLElement).style.borderColor = "var(--accent-primary)"; (e.target as HTMLElement).style.boxShadow = "0 0 0 3px var(--accent-muted)"; }}
                  onBlur={(e) => { (e.target as HTMLElement).style.borderColor = "var(--border-default)"; (e.target as HTMLElement).style.boxShadow = "none"; }}
                />
              </div>

              {/* Visibility */}
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setIsPrivate(true)}
                  className="flex-1 rounded-lg px-4 py-3 text-left transition-all duration-[180ms]"
                  style={{
                    backgroundColor: isPrivate ? "var(--accent-muted)" : "var(--bg-surface)",
                    border: `1px solid ${isPrivate ? "var(--accent-primary)" : "var(--border-default)"}`,
                  }}
                  onMouseEnter={(e) => { if (!isPrivate) { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-strong)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-overlay)"; } }}
                  onMouseLeave={(e) => { if (!isPrivate) { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-default)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-surface)"; } }}
                >
                  <div className="flex items-center gap-2 text-[13px] font-semibold" style={{ color: isPrivate ? "var(--accent-primary)" : "var(--text-primary)" }}>
                    <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                    </svg>
                    Private
                  </div>
                  <p className="mt-1 text-[10px]" style={{ color: isPrivate ? "var(--accent-primary)" : "var(--text-tertiary)" }}>Only you can see</p>
                </button>
                <button
                  type="button"
                  onClick={() => setIsPrivate(false)}
                  className="flex-1 rounded-lg px-4 py-3 text-left transition-all duration-[180ms]"
                  style={{
                    backgroundColor: !isPrivate ? "var(--accent-muted)" : "var(--bg-surface)",
                    border: `1px solid ${!isPrivate ? "var(--accent-primary)" : "var(--border-default)"}`,
                  }}
                  onMouseEnter={(e) => { if (isPrivate) { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-strong)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-overlay)"; } }}
                  onMouseLeave={(e) => { if (isPrivate) { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-default)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-surface)"; } }}
                >
                  <div className="flex items-center gap-2 text-[13px] font-semibold" style={{ color: !isPrivate ? "var(--accent-primary)" : "var(--text-primary)" }}>
                    <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    Public
                  </div>
                  <p className="mt-1 text-[10px]" style={{ color: !isPrivate ? "var(--accent-primary)" : "var(--text-tertiary)" }}>Anyone can see</p>
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        {(step === "form" || step === "validating" || step === "exporting") && (
          <div className="flex items-center justify-between px-6 py-4" style={{ borderTop: "1px solid var(--border-subtle)" }}>
            <button
              type="button"
              onClick={onClose}
              className="rounded-lg px-4 py-2 text-[13px] font-medium transition-all duration-[180ms]"
              style={{ color: "var(--text-tertiary)" }}
              onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.color = "var(--text-primary)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-surface)"; }}
              onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.color = "var(--text-tertiary)"; (e.currentTarget as HTMLElement).style.backgroundColor = "transparent"; }}
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={exportToGitHub}
              disabled={!token.trim() || step === "validating" || step === "exporting"}
              className="inline-flex items-center gap-2 rounded-lg px-5 py-2.5 text-[13px] font-semibold transition-all duration-[180ms] disabled:cursor-not-allowed disabled:opacity-50"
              style={{
                backgroundColor: "var(--accent-primary)",
                color: "var(--text-inverse)",
                letterSpacing: "0.01em",
              }}
              onMouseEnter={(e) => { if (!e.currentTarget.disabled) { (e.currentTarget as HTMLElement).style.backgroundColor = "var(--accent-hover)"; (e.currentTarget as HTMLElement).style.boxShadow = "var(--shadow-glow)"; } }}
              onMouseLeave={(e) => { if (!e.currentTarget.disabled) { (e.currentTarget as HTMLElement).style.backgroundColor = "var(--accent-primary)"; (e.currentTarget as HTMLElement).style.boxShadow = "none"; } }}
            >
              {step === "exporting" ? (
                <>
                  <svg className="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  Exporting...
                </>
              ) : (
                <>
                  <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 24 24">
                    <path fillRule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clipRule="evenodd" />
                  </svg>
                  Push to GitHub
                </>
              )}
            </button>
          </div>
        )}

        {(step === "success" || step === "error") && (
          <div className="px-6 py-4 text-right" style={{ borderTop: "1px solid var(--border-subtle)" }}>
            <button
              type="button"
              onClick={onClose}
              className="rounded-lg px-5 py-2.5 text-[13px] font-semibold transition-all duration-[180ms]"
              style={{ backgroundColor: "var(--bg-surface)", border: "1px solid var(--border-default)", color: "var(--text-primary)" }}
              onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-strong)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-overlay)"; }}
              onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.borderColor = "var(--border-default)"; (e.currentTarget as HTMLElement).style.backgroundColor = "var(--bg-surface)"; }}
            >
              Close
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
