/**
 * GitHub Export Routes
 * 
 * Creates a real GitHub repository and pushes generated code using
 * the GitHub REST API with a Personal Access Token.
 */

import { FastifyInstance } from 'fastify';
import { prisma } from '../lib/prisma.js';
import { getRequestUser } from '../lib/auth.js';
import { createUserNotification } from '../lib/notifications.js';
import { generateStandaloneProject } from '../generators/github-export.js';

interface GitHubTreeItem {
  path: string;
  mode: '100644';
  type: 'blob';
  content: string;
}

// Friendly error messages for common GitHub API errors
const GITHUB_ERROR_HINTS: Record<string, string> = {
  'Resource not accessible by personal access token':
    'Your token does not have permission to create repositories. Please use a Classic token with the "repo" scope. Fine-grained tokens need "Administration: Read & Write" + "Contents: Read & Write" permissions.',
  'Not Found':
    'Repository or resource not found. Your token may lack access to this repository.',
  'Validation Failed':
    'GitHub rejected the request. The repository name may contain invalid characters.',
  'Bad credentials':
    'Your GitHub token is invalid or has expired. Please generate a new one.',
};

function friendlyGitHubError(rawMessage: string): string {
  for (const [key, hint] of Object.entries(GITHUB_ERROR_HINTS)) {
    if (rawMessage.includes(key)) {
      return hint;
    }
  }
  return rawMessage;
}

async function githubApi(path: string, token: string, options: RequestInit = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
  });

  const body = await res.json().catch(() => ({}));

  if (!res.ok) {
    const rawMsg = (body as any).message || `GitHub API error: ${res.status} ${res.statusText}`;
    const err = new Error(friendlyGitHubError(rawMsg));
    (err as any).status = res.status;
    (err as any).raw = rawMsg;
    throw err;
  }

  return body;
}

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/** Retry fetching a ref — GitHub can take a moment after auto_init */
async function getRefWithRetry(
  repoFullName: string,
  branch: string,
  token: string,
  maxRetries = 6
): Promise<{ commitSha: string; treeSha: string }> {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const ref: any = await githubApi(
        `/repos/${repoFullName}/git/ref/heads/${branch}`,
        token
      );
      const commit: any = await githubApi(
        `/repos/${repoFullName}/git/commits/${ref.object.sha}`,
        token
      );
      return { commitSha: ref.object.sha, treeSha: commit.tree.sha };
    } catch (err: any) {
      const msg = err.raw || err.message || '';
      const isEmptyRepo = msg.includes('Git Repository is empty') || msg.includes('Not Found');

      if (isEmptyRepo && attempt === maxRetries) {
        // Repo exists but is completely empty — seed it via Contents API
        // (Contents API works on empty repos, Git Data API does not)
        console.log(`[GitHub] Repo ${repoFullName} is empty, seeding via Contents API...`);
        await githubApi(
          `/repos/${repoFullName}/contents/README.md`,
          token,
          {
            method: 'PUT',
            body: JSON.stringify({
              message: 'Initial commit',
              content: Buffer.from(`# ${repoFullName.split('/')[1]}\n\nGenerated by MetaForge.\n`).toString('base64'),
            }),
          }
        );
        // Now retry once more to get the ref
        await sleep(2000);
        const ref: any = await githubApi(
          `/repos/${repoFullName}/git/ref/heads/${branch}`,
          token
        );
        const commit: any = await githubApi(
          `/repos/${repoFullName}/git/commits/${ref.object.sha}`,
          token
        );
        return { commitSha: ref.object.sha, treeSha: commit.tree.sha };
      }

      if (attempt < maxRetries) {
        await sleep(attempt * 1000);
        continue;
      }
      throw err;
    }
  }
  throw new Error('Failed to read repository ref after creation');
}

function exportConfigForApp(found: { name: string; description: string | null; configJson: any }) {
  const config = found.configJson && typeof found.configJson === 'object'
    ? { ...found.configJson }
    : {};

  return {
    ...config,
    app: {
      name: config.app?.name || found.name,
      description: config.app?.description || found.description || 'Generated with MetaForge',
      ...(config.app || {}),
    },
    entities: Array.isArray(config.entities) ? config.entities : [],
    pages: Array.isArray(config.pages) ? config.pages : [],
    workflows: Array.isArray(config.workflows) ? config.workflows : [],
  };
}

export async function githubRoutes(app: FastifyInstance) {

  // POST /api/v1/github/export/:appId — Push generated code to a new GitHub repo
  app.post('/github/export/:appId', async (request, reply) => {
    const { appId } = request.params as { appId: string };
    const body = request.body as {
      token: string;
      repoName?: string;
      isPrivate?: boolean;
      description?: string;
    };

    if (!body.token) {
      return reply.status(400).send({
        success: false,
        error: { code: 'MISSING_TOKEN', message: 'GitHub personal access token is required' },
      });
    }

    const user = getRequestUser(request);
    const found = await prisma.app.findUnique({ where: { id: appId } });
    if (!found) {
      return reply.status(404).send({
        success: false,
        error: { code: 'NOT_FOUND', message: 'App not found' },
      });
    }
    if (user.role !== 'admin' && found.ownerId !== user.id) {
      return reply.status(403).send({
        success: false,
        error: { code: 'FORBIDDEN', message: 'You do not have access to this app' },
      });
    }

    const config = exportConfigForApp(found);
    const files = generateStandaloneProject(config);
    const repoName = body.repoName ||
      found.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'metaforge-app';

    try {
      // 1. Validate token — get authenticated user + check scopes
      const ghUser: any = await githubApi('/user', body.token);

      // 2. Create repository with auto_init so GitHub creates an initial commit
      //    (Git Data API requires at least one commit to exist)
      let repo: any;
      try {
        repo = await githubApi('/user/repos', body.token, {
          method: 'POST',
          body: JSON.stringify({
            name: repoName,
            description: body.description || config.app?.description || `${found.name} — Generated by MetaForge`,
            private: body.isPrivate !== false,
            auto_init: true,
          }),
        });
      } catch (err: any) {
        if (err.raw?.includes('already exists') || err.message?.includes('already exists')) {
          // Repo already exists — fetch it
          repo = await githubApi(`/repos/${ghUser.login}/${repoName}`, body.token);
        } else {
          throw err;
        }
      }

      const owner = repo.owner?.login || ghUser.login;
      const repoFullName = `${owner}/${repoName}`;
      const defaultBranch = repo.default_branch || 'main';

      // 3. Wait for the initial commit to be ready (GitHub needs a moment after auto_init)
      const refData = await getRefWithRetry(repoFullName, defaultBranch, body.token);
      const latestCommitSha = refData.commitSha;
      const baseTreeSha = refData.treeSha;

      // 4. Build a tree from all generated files
      const treeItems: GitHubTreeItem[] = files.map(file => ({
        path: file.path,
        mode: '100644' as const,
        type: 'blob' as const,
        content: file.content,
      }));

      const newTree: any = await githubApi(
        `/repos/${repoFullName}/git/trees`,
        body.token,
        {
          method: 'POST',
          body: JSON.stringify({ base_tree: baseTreeSha, tree: treeItems }),
        }
      );

      // 5. Create commit
      const newCommit: any = await githubApi(
        `/repos/${repoFullName}/git/commits`,
        body.token,
        {
          method: 'POST',
          body: JSON.stringify({
            message: `MetaForge export: ${found.name} (v${found.configVersion})`,
            tree: newTree.sha,
            parents: [latestCommitSha],
          }),
        }
      );

      // 6. Update the default branch ref
      await githubApi(
        `/repos/${repoFullName}/git/refs/heads/${defaultBranch}`,
        body.token,
        {
          method: 'PATCH',
          body: JSON.stringify({ sha: newCommit.sha, force: true }),
        }
      );

      // Notify user
      await createUserNotification({
        userId: found.ownerId,
        type: 'github_export_success',
        title: `${found.name} exported to GitHub`,
        message: `Your app has been pushed to github.com/${repoFullName} with ${files.length} files.`,
        appId: found.id,
        metadata: {
          repository: repoFullName,
          url: repo.html_url,
          fileCount: files.length,
          commitSha: newCommit.sha,
        },
      });

      return {
        success: true,
        data: {
          repository: repoFullName,
          url: repo.html_url,
          commitSha: newCommit.sha,
          branch: defaultBranch,
          fileCount: files.length,
          files: files.map(f => ({ path: f.path, size: f.content.length })),
        },
      };

    } catch (err: any) {
      const errorMsg = err.message || 'An unknown error occurred during GitHub export.';

      await createUserNotification({
        userId: found.ownerId,
        type: 'github_export_failed',
        title: `GitHub export failed for ${found.name}`,
        message: errorMsg,
        appId: found.id,
        metadata: { error: errorMsg },
      });

      return reply.status(500).send({
        success: false,
        error: { code: 'GITHUB_EXPORT_FAILED', message: errorMsg },
      });
    }
  });

  // POST /api/v1/github/validate-token — Validate a GitHub token and check scopes
  app.post('/github/validate-token', async (request, reply) => {
    const { token } = request.body as { token?: string };
    if (!token) {
      return reply.status(400).send({
        success: false,
        error: { code: 'MISSING_TOKEN', message: 'Token is required' },
      });
    }

    try {
      // Make a raw fetch so we can read the X-OAuth-Scopes header
      const res = await fetch('https://api.github.com/user', {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
      });

      if (!res.ok) {
        return reply.status(401).send({
          success: false,
          error: { code: 'INVALID_TOKEN', message: 'The provided GitHub token is invalid or expired' },
        });
      }

      const ghUser = await res.json() as any;
      const scopes = res.headers.get('x-oauth-scopes') || '';
      const scopeList = scopes.split(',').map((s: string) => s.trim()).filter(Boolean);
      const hasRepoScope = scopeList.includes('repo') || scopeList.length === 0; // fine-grained tokens have no scopes header

      return {
        success: true,
        data: {
          login: ghUser.login,
          name: ghUser.name,
          avatarUrl: ghUser.avatar_url,
          publicRepos: ghUser.public_repos,
          scopes: scopeList,
          hasRepoScope,
          tokenType: scopeList.length === 0 ? 'fine-grained' : 'classic',
        },
      };
    } catch (err: any) {
      return reply.status(401).send({
        success: false,
        error: { code: 'INVALID_TOKEN', message: 'The provided GitHub token is invalid or expired' },
      });
    }
  });
}
